version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: banco
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
